#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat May 23 10:47:15 2020

@author: anton
"""

from SLiCAP import *
prj = initProject('My first SLiCAP project') # Creates the SLiCAP libraries and the
                          # project HTML index page

fileName = 'PIVA.cir'
i1 = instruction()           # Creates an instance of an instruction object
i1.checkCircuit(fileName)    # Checks and defines the local circuit object and
                             # resets the index page to the project index page
htmlPage('Circuit data')     # Creates an HTML page and a link on the index page
                             # of this circuit
netlist2html(fileName)       # Netlist of the circuit
elementData2html(i1.circuit) # Element data of a circuit
params2html(i1.circuit)      # Parameters of the last circuit checked

fileName = 'MOSamp.cir'
i2 = instruction()           # Creates an instance of an instruction object
i2.checkCircuit(fileName)    # Checks and defines the local circuit object and
                             # resets the index page to the project index page
htmlPage('Circuit data')     # Creates an HTML page and a link on the index page
                             # of this circuit
netlist2html(fileName)       # Netlist of the circuit
elementData2html(i2.circuit) # Element data of the last circuit checked
params2html(i2.circuit)      # Parameters of the last circuit checked

print i1.circuit.title
print i1.circuit.elements.keys()

print i2.circuit.title
print i2.circuit.elements.keys()

"""
You can place links and text on any HTML page, but you need to know the names
that are automatically generated by SLiCAP.

You can get the name of the page of a label with getLabels(<labelName>).
"""

HTMLindex('index.html')   # Resets the HTML index page to the project index
                          # page
htmlPage('Another page')  # Creates another page with a link on the main index
                          # and makes this page the active HTML page.
HTMLindex('MOSamp_index.html') # Makes the MOSamp_index.html page the active
                          # index page
htmlPage('Another MOSamp page') # Creates a new HTML page with a link on the
                          # active index page
HTMLpage('PIVA_Circuit-data.html') # Makes this page the active HTML page
text2html('This concludes the PIVA circuit data section.')             

prj.close()