{   'C': Device(ID='C', nNodes=2, nRefs=0, value=True, models=['C']),
    'D': Device(ID='D', nNodes=2, nRefs=0, value=True, models=['D']),
    'E': Device(ID='E', nNodes=4, nRefs=0, value=True, models=['E', 'EZ']),
    'F': Device(ID='F', nNodes=4, nRefs=0, value=True, models=['F']),
    'G': Device(ID='G', nNodes=4, nRefs=0, value=True, models=['G', 'g']),
    'H': Device(ID='H', nNodes=4, nRefs=0, value=True, models=['H', 'HZ']),
    'I': Device(ID='I', nNodes=2, nRefs=0, value=True, models=['I']),
    'J': Device(ID='J', nNodes=3, nRefs=0, value=True, models=['J']),
    'K': Device(ID='K', nNodes=0, nRefs=2, value=True, models=['K']),
    'L': Device(ID='L', nNodes=2, nRefs=0, value=True, models=['L']),
    'M': Device(ID='M', nNodes=4, nRefs=0, value=True, models=['M', 'MD']),
    'N': Device(ID='N', nNodes=4, nRefs=0, value=False, models=['N']),
    'O': Device(ID='O', nNodes=4, nRefs=0, value=True, models=['OC', 'OV']),
    'Q': Device(ID='Q', nNodes=4, nRefs=0, value=True, models=['QV', 'QD', 'QL']),
    'R': Device(ID='R', nNodes=2, nRefs=0, value=True, models=['R', 'r']),
    'T': Device(ID='T', nNodes=4, nRefs=0, value=True, models=['T']),
    'V': Device(ID='V', nNodes=2, nRefs=0, value=True, models=['V']),
    'W': Device(ID='W', nNodes=4, nRefs=0, value=True, models=['W']),
    'X': Device(ID='X', nNodes=-1, nRefs=0, value=None, models=[])}
