{ 'C': Model(name='C', stamp=True, depVars=[], params={'value': False, 'vinit': False}),
  'D': Model(name='D', stamp=False, depVars=[], params={'rs': False, 'cd': False, 'gd': False}),
  'E': Model(name='E', stamp=True, depVars=['Io'], params={'value': True}),
  'EZ': Model(name='EZ', stamp=True, depVars=['Io'], params={'value': True, 'zo': True}),
  'F': Model(name='F', stamp=True, depVars=['Ii'], params={'value': True}),
  'G': Model(name='G', stamp=True, depVars=['Io'], params={'value': True}),
  'H': Model(name='H', stamp=True, depVars=['Io', 'Ii'], params={'value': True}),
  'HZ': Model(name='HZ', stamp=True, depVars=['Io', 'Ii'], params={'value': True, 'zo': True}),
  'I': Model(name='I', stamp=True, depVars=[], params={'value': True, 'dc': False, 'dcvar': False, 'noise': False}),
  'J': Model(name='J', stamp=False, depVars=[], params={'cgs': False, 'cdg': False, 'gm': False, 'go': False}),
  'K': Model(name='K', stamp=True, depVars=[], params={'value': False}),
  'L': Model(name='L', stamp=True, depVars=['I'], params={'value': False, 'iinit': False}),
  'M': Model(name='M', stamp=False, depVars=[], params={'cgs': False, 'cdg': False, 'cdb': False, 'csb': False, 'cgb': False, 'gm': False, 'gb': False, 'go': False}),
  'MD': Model(name='MD', stamp=False, depVars=[], params={'cgg': False, 'cdg': False, 'cdd': False, 'gm': False, 'go': False}),
  'N': Model(name='N', stamp=True, depVars=['Io'], params={}),
  'OC': Model(name='OC', stamp=False, depVars=[], params={'cp': False, 'gp': False, 'cpn': False, 'gpn': False, 'gm': False, 'zt': True, 'zo': True}),
  'OV': Model(name='OV', stamp=False, depVars=[], params={'cd': False, 'cc': False, 'gd': False, 'gc': False, 'av': True, 'zo': True}),
  'QD': Model(name='QD', stamp=False, depVars=[], params={'cbb': False, 'cbc': False, 'gbb': False, 'gm': False, 'gcc': False, 'gbc': False, 'rb': False}),
  'QL': Model(name='QL', stamp=False, depVars=[], params={'cpi': False, 'cbc': False, 'cbx': False, 'cs': False, 'gpi': False, 'gm': False, 'gbc': False, 'go': False, 'rb': False}),
  'QV': Model(name='QV', stamp=False, depVars=[], params={'cpi': False, 'cbc': False, 'cbx': False, 'cs': False, 'gpi': False, 'gm': False, 'gbc': False, 'go': False, 'rb': False}),
  'R': Model(name='R', stamp=True, depVars=[], params={'value': False, 'dcvar': False, 'noisetemp': False, 'noiseflow': False}),
  'T': Model(name='T', stamp=True, depVars=['Io'], params={'value': False}),
  'V': Model(name='V', stamp=True, depVars=['I'], params={'value': True, 'dc': False, 'dcvar': False, 'noise': False}),
  'W': Model(name='W', stamp=True, depVars=[], params={'value': False}),
  'g': Model(name='g', stamp=True, depVars=[], params={'value': False}),
  'r': Model(name='r', stamp=True, depVars=['I'], params={'value': False, 'dcvar': False, 'noisetemp': False, 'noiseflow': False})}
